### ISSUE TITLE
<SLY> Tag not working

### ISSUE THREAD

**Issue by ErikGrijzen** [Adobe-Marketing-Cloud/sightly-spec#10]
For some reason the SLY element tag is not working in Sightly. See spec:

https://github.com/Adobe-Marketing-Cloud/sightly-spec/blob/master/SPECIFICATION.md#31-sly

It renders the sly element in the HTML and is not unwrapping the element automatically. Tested it with multiply block statements.

**Comment by raducotescu** [comment]
@ErikGrijzen, an implementation of the 1.1 version of the language specification will be available in AEM 6.1.
