### ISSUE TITLE
Add "since" version for each feature

### ISSUE THREAD

**Issue by gabrielwalt** [Adobe-Marketing-Cloud/sightly-spec#13]
Looking at the spec, it is currently unclear for the reader when new features got introduced. All features should document since which version of Sightly they are available.

E.g.:
**3.1. &lt;sly&gt;**
Since: Sightly 1.1
The <sly> HTML tag can be used to remove the current element [...]

**Comment by raducotescu** [comment]
@gabrielwalt, do you still find this useful given that we've fixed #16?

**Comment by gabrielwalt** [comment]
No, you're right that's not needed anymore then. Also the language isn't making big changes, so I don't think that there's such a need for being that specific on when each feature has been added.
