### ISSUE TITLE
Support sending a redirect

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/sightly-spec#18]
Similar to what <c:redirect> does for JSPs (http://www.tutorialspoint.com/jsp/jstl_core_redirect_tag.htm) Sightly should have a block element which allows to send a redirect back to the browser.
Currently this is only possible with Javascript/Java objects called via the Use-API.

**Comment by raducotescu** [comment]
@kwin, a redirect feature is not one related to templating. Redirects can easily be added through Use objects and Sightly's main goal is to separate logic from templates.
