### ISSUE TITLE
Allow Java Enums to be used in comparisons

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Marketing-Cloud/sightly-spec#19]
Per https://issues.apache.org/jira/browse/SLING-5053, there is desire to change the casting behavior from Enums to Strings. This should be reflected in the spec.

**Comment by raducotescu** [comment]
SLING-5053 does not mention anything about Enums being casted to Strings, but allowing Enums to be used in comparisons, which was what the specification should have defined first. However, given that I work on both projects I've firstly created the SLING issue.

**Comment by justinedelson** [comment]
Ah, my misunderstanding. I assumed when I saw

    ${some.thing == 'VALUE'}

That meant that some.thing's toString() method was being called and then compared to the RHS. But I see that it is actually the reverse. Much better that way :+1:
