### ISSUE TITLE
data-sly-repeat

### ISSUE THREAD

**Issue by heervisscher** [Adobe-Marketing-Cloud/sightly-spec#4]
I want to propose a new operation in Sightly: data-sly-repeat.
This to overcome situations where you want to loop through items, but where you don't have a container element in your markup.

This is possible with data-sly-list and data-sly-unwrap, but that forces you to add markup.

```
<div data-sly-list="${resource.listChildren}" data-sly-unwrap>
   <div>${child.path}</div>
</div>
```

With data-sly-repeat you would be able to write it like this:

```
<div data-sly-repeat="${resource.listChildren}">${child.path}</div>
```

**Comment by raducotescu** [comment]
Fixed in f2afcf2.
