### ISSUE TITLE
Allow array join to passthrough strings

### ISSUE THREAD

**Issue by vladbailescu** [Adobe-Marketing-Cloud/sightly-spec#7]
I propose to modify the Sightly spec so that the [array join](https://github.com/Adobe-Marketing-Cloud/sightly-spec/blob/master/SPECIFICATION.md#124-array-join) works on simple strings by passing them through: `${'test' @ join=', '}` will output `test`

Right now we must wrap the string into an ugly single-element array: `${['test'] @ join=', '}`

**Comment by raducotescu** [comment]
Fixed in f2afcf2.
