### ISSUE TITLE
Wrong example in repeat

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/sightly-spec#9]
In https://github.com/Adobe-Marketing-Cloud/sightly-spec/blob/1.1/SPECIFICATION.md#227-repeat the example is saying 
`data-sly-list.childResource="${resource.listChildren}"` where it should say `data-sly-repeat.childResource="${resource.listChildren}"`

**Comment by raducotescu** [comment]
Thanks for spotting this. I'll correct it right away.
